#!/bin/bash
#
# this is really greedy...
#

function rmtags() {
	sed "s@</\?$1\>[^>]*>@@g";
}

function rmtagsbody() {
	sed "s@<$1\>[^>]*>[^<]*</$1>@@g";
}

function subtags() {
	sed "s@<$1>\([^<]*\)</$1>@$2\1$3@g"
}


cat | \
	tr -d "\n"							| \
	tr "\t" " "							| \
	sed "s/ \+/ /g"							| \
	rmtags "!doctype"						| \
	rmtags "html"							| \
	rmtags "META"							| \
	rmtags "head"							| \
	rmtags "body"							| \
	rmtags "table"							| \
	rmtags "tr"							| \
	rmtags "td"							| \
	rmtags "center"							| \
	rmtags "font"							| \
	rmtags "dl"							| \
	subtags "b" '**{{{' '}}}**'					| \
	sed "s/{{{\([^}]*\)[[:space:]]\+}}}/\1/g"			| \
	sed "s/{{{\([^}]*\)}}}/\1/g"					| \
	subtags "i" '//' '//'						| \
	subtags "li" '* ' '{{NEWLINE}}'					| \
	subtags "title" '{{NEWLINE}}+ ' '{{NEWLINE}}'			| \
	subtags "h1" '{{NEWLINE}}+ ' '{{NEWLINE}}'			| \
	subtags "h2" '{{NEWLINE}}++ ' '{{NEWLINE}}'			| \
	subtags "h3" '{{NEWLINE}}+++ ' '{{NEWLINE}}'			| \
	subtags "h4" '{{NEWLINE}}++++ ' '{{NEWLINE}}'			| \
	sed "s/<img\>[^>]*src=\"\([^>]*\)\"[^>]*>/[[image \1]]/g"	| \
	subtags "div" '{{NEWLINE}}' '{{NEWLINE}}'			| \
	subtags "dt" '* ' '.'						| \
	subtags "dd" '' '{{NEWLINE}}'					| \
	subtags "dd" '' '{{NEWLINE}}'					| \
	sed "s@</\?p>@{{NEWLINE}}@g"					| \
	sed "s@</\?ul>@{{NEWLINE}}@g"					| \
	sed "s/^[[:space:]]*//"						| \
	sed "s@\(\[\[image[[:space:]]\+\)\.\./images/\(.*\]\]\)@\1\2@g"	| \
	sed "s/ \+/ /g"							| \
	sed "s/[[:space:]]*{{NEWLINE}}[[:space:]]*/\n/g"				| \
	cat -s
echo
