# Install help files
helpdir = datadir / 'help' / 'gimp-lqr-plugin'

message('Help installation path: ' + helpdir)

install_subdir('en',
  install_dir : helpdir,
  strip_directory : true
)
install_subdir('it',
  install_dir : helpdir,
  strip_directory : true
)
install_subdir('ru',
  install_dir : helpdir,
  strip_directory : true
)
install_subdir('es_ES',
  install_dir : helpdir,
  strip_directory : true
)
install_subdir('css',
  install_dir : helpdir,
  strip_directory : true
) 